/*
 * Copyright 2021 Wang Min Xiang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gcg

import (
	"fmt"
	"go/format"
	"golang.org/x/tools/imports"
	"io"
)

const (
	fileHeadNote = "// NOTE: This file has been automatically generated by github.com/aacfactory/gcg. \n// Dont Edit it."
)

type CodeBlock struct {
}

type File struct {
	packageName string
	imports     Imports
	decls       []Decl
}

func (f *File) Render(w io.Writer) (err error) {

	return
}

func (f *File) reformat(p []byte) (b []byte, err error) {
	b, err = imports.Process("", p, nil)
	if err != nil {
		err = fmt.Errorf("reformat code failed, %v", err)
		return
	}
	b, err = format.Source(b)
	if err != nil {
		err = fmt.Errorf("reformat code failed, %v", err)
		return
	}
	return
}
